version: '3'
services:
  db:
    image: postgres:13.1-alpine
    container_name: nutri-postgres
    environment:
      POSTGRES_USER: nutri
      POSTGRES_PASSWORD: nutri-password
      POSTGRES_DB: nutir
    ports:
    - '5432:5432'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - nutri-data:/var/lib/postgresql/data
volumes:
  nutri-data:
    driver: local

