version: '3'
services:
  db:
    image: postgres:13.1-alpine
    container_name: nutri-postgres13.1-alpine
    environment:
      POSTGRES_USER: nutri
      POSTGRES_PASSWORD: nutri-password
    ports:
    - '54322:5432'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

